name: one_africa_global
description: One Africa Global App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  #firebase_core: ^0.3.4
  #firebase_analytics: ^2.1.1+3
  #cloud_firestore: ^0.10.1
  #firebase_auth: ^0.8.4+5
  #  google_sign_in: ^4.0.1+1


  #firebase_core: ^0.4.0 # add dependency for Firebase Core
  #firebase_auth: ^0.6.6
  #cloud_firestore: ^0.8.2+3
  #firebase_auth: 0.7.0
  #firebase_auth: 0.11.1+6
  #google_sign_in: 3.2.4
  #flutter_facebook_login: 2.0.1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  webview_flutter: ^0.3.4
  marquee_flutter: ^0.1.4
  modal_progress_hud: ^0.1.3
  sweet_alert_dialogs: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: "^0.7.2"

#flutter_icons:
 # ios: true
  #image_path_ios: "assets/icons/logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pobo.png
    - assets/oag1.png
    - assets/images/f.jpg
    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.jpg
    - assets/images/img4.jpg
    - assets/images/img5.jpg
    - assets/images/img6.jpg
    - assets/images/img7.jpg
    - assets/images/img8.jpg
    - assets/images/img9.jpg
    - assets/images/img10.jpg
    - assets/images/img11.jpg
    - assets/images/img12.jpg
    - assets/images/img13.jpg
    - assets/images/img14.jpg
    - assets/images/img15.jpg
    - assets/images/img16.jpg
    - assets/images/img17.jpg
    - assets/images/img18.jpg
    - assets/images/img19.jpg
    - assets/images/img20.jpg
    - assets/images/img21.jpg
    - assets/images/img22.jpg
    - assets/images/img23.jpg
    - assets/images/img24.jpg
    - assets/images/img25.jpg
    - assets/images/img26.jpg
    - assets/images/img27.jpg
    - assets/images/img28.jpg
    - assets/images/img29.jpg
    - assets/images/img30.jpg
    - assets/images/img31.jpg
    - assets/images/img32.jpg
    - assets/images/img33.jpg
    - assets/images/img34.jpg
    - assets/images/img35.jpg
    - assets/images/img36.jpg
    - assets/images/img37.jpg
    - assets/images/img38.jpg
    - assets/lp.png
    - assets/oab.png
    - assets/upgmc.png
    - assets/oagf.png
    - assets/oar.png
    - assets/oafc.png
    - assets/ioamf.png
    - assets/help.png
    - assets/facebook.png
    - assets/instagram.png
    - assets/twitter.png
    - assets/logo2.png
    - assets/settings.png
    - assets/play.png
    - assets/favicon.png


  #  - images/a_dot_ham.jpeg
  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

    - family:  CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
